STATIC_FEATURES = [
    'conv3',
    # 'ColorName',
    'HoG',
]

IMPUT_SAMPLE_SIZE = 224
STATIC_FEATURE_SIZE = 224

PERFORM_BBOX_REG = False

BATCH_SIZE = 128

SEARCH_AREA_SIZE_RATIO = 2

GAUSSIAN_LABEL_SIGMA = 0.36
GAUSSIAN_LABEL_AMPLITUDE = 1

INIT_TRAIN_ITER = 10
TRAIN_ITER_PER_ROUND = 5

MOMENTOM = 0.9
WEIGHT_DECAY = 1e-4
LEARNING_RATE = 0.01
